import type { Caption, CaptionStyle, WordTiming } from "@/types";

/**
 * Builds an .ass subtitle file that FFmpeg's libass filter burns into the
 * export. The geometry uses PlayResX/Y = 1080x1920, so every pixel value in
 * CaptionStyle maps 1:1 onto the export — this is what keeps the live preview
 * and the final video in sync.
 *
 * Besides captions this also renders text-graphic and sticker clips as
 * positioned events (\pos on the same 1080x1920 canvas as the preview).
 */

const CANVAS_W = 1080;
const CANVAS_H = 1920;

/**
 * Vertical placement, expressed as bottom margins for bottom-anchored text.
 * "bottom" stays above the TikTok UI zone (username/caption/music ≈ bottom 300px).
 */
const POSITION_MARGIN_V: Record<CaptionStyle["position"], number> = {
  center: 0, // uses middle-center alignment instead
  lower: 560,
  bottom: 330,
};

/** A text/sticker clip flattened for burn-in. Coordinates = canvas-center offsets. */
export interface AssOverlayEvent {
  text: string;
  start: number;
  end: number;
  x: number;
  y: number;
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  color: string;
  strokeColor: string;
  strokeWidth: number;
  backgroundColor: string | null;
  sticker?: boolean;
}

export function buildAss(
  captions: Caption[],
  style: CaptionStyle,
  overlays: AssOverlayEvent[] = []
): string {
  const alignment = style.position === "center" ? 5 : 2; // 5 = middle-center, 2 = bottom-center
  const marginV = POSITION_MARGIN_V[style.position];

  const hasBox = style.backgroundColor !== null;
  const primary = assColor(style.textColor);
  // With BorderStyle 3 the "outline" becomes an opaque box: OutlineColour is
  // the box color and Outline is its padding. Stroke and box are exclusive.
  const outlineColor = hasBox
    ? assColor(style.backgroundColor as string, 1 - style.backgroundOpacity)
    : assColor(style.strokeColor);
  const backColor = hasBox
    ? assColor(style.backgroundColor as string, 1 - style.backgroundOpacity)
    : assColor("#000000", 0.5);
  const borderStyle = hasBox ? 3 : 1;
  const outline = hasBox ? 18 : style.strokeWidth;
  const shadow = hasBox ? 0 : style.shadow ? 3 : 0;
  const bold = style.fontWeight >= 700 ? -1 : 0;

  const styleLines = [
    `Style: Caption,${style.fontFamily},${style.fontSize},${primary},${primary},${outlineColor},${backColor},${bold},0,0,0,100,100,0,0,${borderStyle},${outline},${shadow},${alignment},70,70,${marginV},1`,
  ];

  // One style per overlay (they're few and independent).
  overlays.forEach((ov, i) => {
    const ovHasBox = ov.backgroundColor !== null;
    const ovOutlineColor = ovHasBox ? assColor(ov.backgroundColor as string, 0.05) : assColor(ov.strokeColor);
    const ovBack = ovHasBox ? assColor(ov.backgroundColor as string, 0.05) : assColor("#000000", 0.5);
    const family = ov.sticker ? "Segoe UI Emoji" : ov.fontFamily;
    styleLines.push(
      `Style: Ov${i},${family},${ov.fontSize},${assColor(ov.color)},${assColor(ov.color)},${ovOutlineColor},${ovBack},${
        ov.fontWeight >= 700 ? -1 : 0
      },0,0,0,100,100,0,0,${ovHasBox ? 3 : 1},${ovHasBox ? 16 : ov.strokeWidth},${ov.sticker ? 0 : 2},5,20,20,0,1`
    );
  });

  const header = `[Script Info]
; Generated by CaptionCut
ScriptType: v4.00+
PlayResX: ${CANVAS_W}
PlayResY: ${CANVAS_H}
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
${styleLines.join("\n")}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const events: string[] = [];
  const sorted = [...captions].sort((a, b) => a.startTime - b.startTime);

  const displayText = (w: string) => escapeAss(style.allCaps ? w.toUpperCase() : w);
  const primaryTag = assColorTag(style.textColor);
  const styleBold = style.fontWeight >= 700;

  /** Render one word with emphasis (bold + emphasis color) and optional highlight. */
  const renderWord = (w: WordTiming, highlighted: boolean): string => {
    let open = "";
    let close = "";
    if (w.emphasis && !styleBold) {
      open += "{\\b1}";
      close = "{\\b0}" + close;
    }
    const color = highlighted
      ? style.highlightColor
      : w.emphasis
        ? style.emphasisColor ?? null
        : null;
    if (color) {
      open += `{\\1c${assColorTag(color)}}`;
      close = `{\\1c${primaryTag}}` + close;
    }
    return open + displayText(w.word) + close;
  };

  for (const cap of sorted) {
    const words = cap.words;
    const hasEmphasis = words?.some((w) => w.emphasis) ?? false;

    if (style.highlightColor && words && words.length > 0) {
      // One dialogue event per spoken word: the active word is recolored.
      // Frame boundaries are word end-times so the caption never blinks off.
      for (let k = 0; k < words.length; k++) {
        const start = k === 0 ? cap.startTime : Math.max(cap.startTime, words[k - 1].endTime);
        const end = k === words.length - 1 ? cap.endTime : Math.min(cap.endTime, words[k].endTime);
        if (end <= start) continue;

        const text = words.map((w, j) => renderWord(w, j === k)).join(" ");
        events.push(dialogue(start, end, "Caption", text));
      }
    } else if (hasEmphasis && words && words.length > 0) {
      const text = words.map((w) => renderWord(w, false)).join(" ");
      events.push(dialogue(cap.startTime, cap.endTime, "Caption", text));
    } else {
      events.push(dialogue(cap.startTime, cap.endTime, "Caption", displayText(cap.text)));
    }
  }

  overlays.forEach((ov, i) => {
    const px = Math.round(CANVAS_W / 2 + ov.x);
    const py = Math.round(CANVAS_H / 2 + ov.y);
    // Layer 1 keeps overlays above simultaneous captions.
    events.push(
      `Dialogue: 1,${assTime(ov.start)},${assTime(ov.end)},Ov${i},,0,0,0,,{\\pos(${px},${py})}${escapeAss(ov.text)}`
    );
  });

  return header + events.join("\n") + "\n";
}

function dialogue(start: number, end: number, styleName: string, text: string): string {
  return `Dialogue: 0,${assTime(start)},${assTime(end)},${styleName},,0,0,0,,${text}`;
}

/** ASS time format: h:mm:ss.cc */
function assTime(seconds: number): string {
  const s = Math.max(0, seconds);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = Math.floor(s % 60);
  const cs = Math.floor((s % 1) * 100);
  return `${h}:${pad2(m)}:${pad2(sec)}.${pad2(cs)}`;
}

function pad2(n: number): string {
  return n.toString().padStart(2, "0");
}

/** "#RRGGBB" -> "&HAABBGGRR" (ASS is alpha+BGR; alpha 00 = opaque). */
function assColor(hex: string, alphaFraction = 0): string {
  const { r, g, b } = parseHex(hex);
  const a = Math.round(Math.min(1, Math.max(0, alphaFraction)) * 255);
  return `&H${toHex(a)}${toHex(b)}${toHex(g)}${toHex(r)}`;
}

/** Inline override color tag value: "&HBBGGRR&". */
function assColorTag(hex: string): string {
  const { r, g, b } = parseHex(hex);
  return `&H${toHex(b)}${toHex(g)}${toHex(r)}&`;
}

function parseHex(hex: string): { r: number; g: number; b: number } {
  const clean = hex.replace("#", "");
  return {
    r: parseInt(clean.slice(0, 2), 16) || 0,
    g: parseInt(clean.slice(2, 4), 16) || 0,
    b: parseInt(clean.slice(4, 6), 16) || 0,
  };
}

function toHex(n: number): string {
  return n.toString(16).padStart(2, "0").toUpperCase();
}

/** Braces open ASS override blocks; newlines break the event line. */
function escapeAss(text: string): string {
  return text.replace(/\{/g, "(").replace(/\}/g, ")").replace(/[\r\n]+/g, " \\N ");
}
